### ISSUE TITLE
New 2DS XL compatability? 

### ISSUE THREAD

**Issue by zjDrummond** [rorosaurus/3ds-usb-c#1]
How hard would it be to modify your board for installation into the New 2DS XL? Possible at all? Any chance we could fund a new board? I just bought a New 2DS XL, and I'd like to add it to my daily travel bad without the worry of charging issues.

**Comment by rorosaurus** [comment]
I have no plans to create that at this time. It's probably do-able, just involves taking measurements and ensuring the parts line up. The PCB design (traces, holes) would be identical apart from the outer shape.
